### PR TITLE
changes for dumb-init usage

### PR DESCRIPTION
**Pull request by billimek**
- Switching to phusion/baseimage
- Invoking worker via `dumb-init` instead of `exec`

### CODE REVIEW

**Comment by billimek** [comment]
As discussed in Slack.  This should also 'fix' #5

**Comment by gregarcara** [comment]
Do you think we need to use the phusion base image as well as the dumb-init? I was hoping just the dumb-init would be enough. And if you use Phusion, wouldn't you want to use /sbin/my_init?

**Comment by billimek** [comment]
Both very good questions.  I'll switch it back to `debian:jessie` and test for the zombie issue. Outcome of that may be an update to this PR..

**Comment by gregarcara** [comment]
It it probably worth adding the dumb-init to the web worker as well since it's a free change.

**Comment by billimek** [comment]
Ok, how about this?  The zombie issue doesn't seem to be present with jessie either so as you say it was redundant to use dumb-init with phusion images.

**Comment by gregarcara** [comment]
This looks good, let me give it a whirl and I can merge this in.

**Comment by gregarcara** [comment]
Works great, merging.

**Pull request merged**
